version: "3.9"

services:
  web:
    environment:
      HOST: 0.0.0.0
    ports:
      # debugger port rubymine
      # for puma in rubymine disable "Debugger" => "Attach to subprocess automaticaly"
      - "127.0.0.1:1234:1234"
      - "127.0.0.1:26166:26168"